// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDObjlSWaNOmNW6_HoEbwkm75o--ywCv58',
    appId: '1:801648424730:web:549193fc6f517dc99b1ea3',
    messagingSenderId: '801648424730',
    projectId: 'newchat-aeb82',
    authDomain: 'newchat-aeb82.firebaseapp.com',
    storageBucket: 'newchat-aeb82.appspot.com',
    measurementId: 'G-3WH58D2JFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8Nr-KOerKA2vaY6eIGFQqLW0eApMEdJo',
    appId: '1:801648424730:android:2265d59a4902097b9b1ea3',
    messagingSenderId: '801648424730',
    projectId: 'newchat-aeb82',
    storageBucket: 'newchat-aeb82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjVHBBz8zv3KOgP2_I6PJNn7RXoeXXbN8',
    appId: '1:801648424730:ios:481199173aea28a19b1ea3',
    messagingSenderId: '801648424730',
    projectId: 'newchat-aeb82',
    storageBucket: 'newchat-aeb82.appspot.com',
    iosClientId: '801648424730-1r2blop6rm8jd949pc5ttn3pavmq171a.apps.googleusercontent.com',
    iosBundleId: 'com.example.newchatapp',
  );
}
